
spring:
  
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/batch?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: curso
      password: Cursocurso1; 
  batch:
    jdbc:
      initialize-schema: "always"
 
      
file:
  input: "entrada.txt"
job:
  parametro: "ejecucion1"

